APPLY_FIXES: all

# Exclude workflow files from auto-fixes for security reasons
APPLY_FIXES_IGNORE:
  - .github/workflows/**

DISABLE_LINTERS:
  - PYTHON_BANDIT
  - PYTHON_BLACK
  - PYTHON_PYRIGHT
  - SPELL_CSPELL

PYTHON_PYLINT_ARGUMENTS: --disable=import-error

VALIDATE_ALL_CODEBASE: true
