APPLY_FIXES: all

DISABLE_LINTERS:
  - PYTHON_BANDIT
  - PYTHON_BLACK
  - SPELL_CSPELL

PYTHON_PYLINT_ARGUMENTS: --disable=import-error

PYTHON_PYRIGHT_ARGUMENTS: --ignore=E0401

VALIDATE_ALL_CODEBASE: true
